In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
np.__version__


'2.5.1'

In [3]:
import numpy as np
print("numpy version:",np.__version__)

numpy version: 2.5.1


In [4]:
[x * 2 for x in [2,3,4]]

[4, 6, 8]

In [5]:
import time 

python_list = list(range(1000000))
numpy_array = np.arange(1000000)

start = time.time()
result_array = [x * 2 for x in python_list]
print("python list time:",time.time() - start,"seconds")

start = time.time()
result_arrat = numpy_array * 2 
print("numpy array time:",time.time() - start,"seconds")

print("python list size:",python_list.__sizeof__(),"bytes")
print("numpy array size :",numpy_array.nbytes,"bytes")

python list time: 0.12171483039855957 seconds
numpy array time: 0.006677389144897461 seconds
python list size: 8000040 bytes
numpy array size : 8000000 bytes


In [6]:
import numpy as np
li = [3,4,5]
print(type(li))
arr = np.array([1,2,3,4,5])
type(arr)

<class 'list'>


numpy.ndarray

In [7]:
arr = np.array([1,2,3,4,5])
print("1D array:",arr)

py_list = [1,2,3,4,5]
print("python list :",py_list)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("\n2D array:\n",arr_2d)

1D array: [1 2 3 4 5]
python list : [1, 2, 3, 4, 5]

2D array:
 [[1 2 3]
 [4 5 6]]


In [8]:
list_1d = [1,2,3,4,5]
arr_1d = np.array(list_1d)
print("from 1D list:",arr_1d)

list_2d = [[1,2,3],[4,5,6]]
arr_2d = np.array(list_2d)
print("\nfrom 2D list:\n",arr_2d)

from 1D list: [1 2 3 4 5]

from 2D list:
 [[1 2 3]
 [4 5 6]]


In [9]:
a=np.array([1,2,3])
a.dtype

dtype('int64')

In [10]:
a

array([1, 2, 3])

In [11]:
int_array = np.array([1,2,3],dtype=np.int32)
float_array = np.array([1.0,2.0,3.0],dtype=np.float64)
bool_array = np.array([True,False,True],dtype=np.str_)
string_array = np.array(["apple","banana","cherry","pineapple","orange"],dtype=np.str_)

print("integer array:",int_array,"Dtype:",int_array.dtype)
print("float array :",float_array,"Dtype:",float_array.dtype)
print("boolean array:",bool_array,"Dtype:",bool_array.dtype)
print("string array :",string_array,"Dtype:",string_array.dtype)

integer array: [1 2 3] Dtype: int32
float array : [1. 2. 3.] Dtype: float64
boolean array: ['True' 'False' 'True'] Dtype: <U5
string array : ['apple' 'banana' 'cherry' 'pineapple' 'orange'] Dtype: <U9


In [12]:
a = [1,2,3]
b = [4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [13]:
a = [1,2,3]
b = [4,5,6]

result = []
for i in range(len(a)):
    for j in range(len(b)):
        if i == j:
            result.append(a[i]+b[j])
print(result)


[5, 7, 9]


In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [16]:
print("\nelement-wise addition:",a+b)
print("subtraction:",a - b)
print("division:",b/a)
print("exponentation:",a**2)
print("modulus:",b%a)


element-wise addition: [5 7 9]
subtraction: [-3 -3 -3]
division: [4.  2.5 2. ]
exponentation: [1 4 9]
modulus: [0 1 0]


In [17]:
a = [1,2,3]
a *3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [18]:
a = np.array([1,2,3])


In [19]:
print("\nscalar addition:", a + 10)
print("scalar multiplication:",a * 2)


scalar addition: [11 12 13]
scalar multiplication: [2 4 6]


In [20]:
arr = np.array([1,2,3,4,5])
print("\nsum:",np.sum(arr))
print("mean:",np.mean(arr))
print("standard deviation:",np.std(arr))
print("minimum:",np.min(arr))
print("maximum:",np.max(arr))
print("index of max:",np.argmax(arr))


sum: 15
mean: 3.0
standard deviation: 1.4142135623730951
minimum: 1
maximum: 5
index of max: 4


In [21]:
arr

array([1, 2, 3, 4, 5])

In [22]:
print("\nall positive?",np.all(arr > 0))
print("any greater than 4?",np.any(arr > 4))


all positive? True
any greater than 4? True


In [23]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("array:\n",arr)
print("\nshape:",arr.shape)
print("size:",arr.size)
print("number of dimensions:",arr.ndim)
print("data type:",arr.dtype)

array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

shape: (3, 3)
size: 9
number of dimensions: 2
data type: int64


In [24]:
#range()function 
range_arr = np.arange(0,10,2)
print("\nrange array:",range_arr)

linspace = np.linspace(0,1,5)    #start , stop ,num_points
print("\nlinearly spaced array:",linspace)


range array: [0 2 4 6 8]

linearly spaced array: [0.   0.25 0.5  0.75 1.  ]


In [25]:
arr = np.array([1,2,3])
print("original array:",arr)

original array: [1 2 3]


In [26]:
arr_appended = np.append(arr,[4,5])
print("after append:",arr_appended)

after append: [1 2 3 4 5]


In [27]:
arr_inserted = np.insert(arr,1,[10,20])
print("after insert:",arr_inserted)

after insert: [ 1 10 20  2  3]


In [28]:
arr_removed = np.delete(arr,[0,2])
print("\nafter delete:",arr_removed)


after delete: [2]


In [29]:
unsorted = np.array([3,1,4,2,5])
sorted_arr = np.sort(unsorted)
print("\nsorted array:",sorted_arr)


sorted array: [1 2 3 4 5]


In [30]:
unsorted.sort()
print("In place sorted :",unsorted)

In place sorted : [1 2 3 4 5]


In [31]:
arr_2d = np.array([[3,2,9],[2,5,4]])
print("\n2D array before sort:\n",arr_2d)
print("sorted along rows:\n", np.sort(arr_2d,axis=1))
print("sorted along columns:\n",np.sort(arr_2d,axis=0))


2D array before sort:
 [[3 2 9]
 [2 5 4]]
sorted along rows:
 [[2 3 9]
 [2 4 5]]
sorted along columns:
 [[2 2 4]
 [3 5 9]]


In [32]:
#3D array

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("array:\n",arr)

array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [33]:
arr.shape

(2, 2, 3)

In [34]:
arr.size


12

In [35]:
arr.ndim

3

In [36]:
len(arr)

2

In [37]:
#can you reshape an array

import numpy as np 
arr = np.arange(12)
print("original array(1D):",arr)

original array(1D): [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
arr_2d = arr.reshape(2,6)
print("\nreshape to 3x4:\n",arr_2d)



reshape to 3x4:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [39]:
arr_3d = arr.reshape(2,3,2)
print("\nreshape to 2x3x2:\n",arr_3d)


reshape to 2x3x2:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [40]:
try:
    arr.reshape(3,4)
    print("\nreshape to (3,4) successful")

    arr.reshape(2,5)
except valueError as e:
    print("\ncannot reshape:",e)


reshape to (3,4) successful


NameError: name 'valueError' is not defined

In [41]:
arr_2d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [43]:
arr_auto = arr.reshape(2,-1)
print("\nauto shaped to 2x6:\n",arr_auto)


auto shaped to 2x6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
arr_copy = arr.copy()
arr_copy.resize(5,3,refcheck = False)
print("\nresized to 5x3 (padded with zeros):\n",arr_copy)


In [ ]:
arr_3d_resize = arr.resize(2,3,2)
print("\nresizedarray:\n",arr_3d_resize)
print("\nresizedarray:\n",arr)

In [ ]:
arr_2 = np.arange(12).reshape(3,4)
arr_2

In [ ]:
arr_ravel = arr_2.ravel()
print("\nflattened array:",arr_ravel)

In [ ]:
arr_2

In [ ]:
arr_ravel[0]=1000
arr_ravel

In [ ]:
arr_2

In [ ]:
arr_3 = np.arange(12).reshape(3,4)
arr_3

arr_flat = arr_3.flatten()
print("\nflattened array:", arr_flat)

In [ ]:
arr_3

In [ ]:
arr_flat[0]=2000
arr_flat


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print("original array (2x3):\n",arr)
print("\nflattened(row-major):",arr.flatten())
print("flattened (column-major):",arr.flatten('F'))

print("\nraveled:",arr.ravel('F'))

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print("original array (2x3):\n",arr)

flat = arr.flatten()
print("\nflattened (copy):",flat)
flat[0] = 100
print("original after modifying flat:",arr[0,0])

raveled = arr.ravel()
print("\nraveled (view):",raveled)
raveled[0] = 100
print("original after modifying raveled:",arr[0,0])

reshaped = arr.reshape(6)
print("\nreshaped to (6,):",reshaped )
reshaped[1] = 200
print("original after modifying reshaped:",arr[0,1])

arr_1d = np.arange(12)
print("\n1D array:",arr_1d)
print("reshaped to 3x4:\n",arr_1d.reshape(3,4))
print("reshaped to 2x3x2:\n",arr_1d.reshape(2,3,2))

    

In [ ]:
arr = np.arange(10)
arr

In [ ]:
arr[6:]



In [ ]:
arr[-1:-5:-1]

In [ ]:
arr[:5:-1]

In [ ]:
arr[::-1]

In [ ]:
arr = np.arange(10)
print("array:",arr)
print("first element:",arr[0])
print("last element:",arr[-1])
print("slice from index 2 to 5:",arr[2:5])
print("reversed array :",arr[::-1])

In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n2D array:\n",arr_2d)
print("element at rows 1, column 2:",arr_2d[1,2])
print("first row:",arr_2d[0,:])
print("last column:",arr_2d[:,-1])
print("sub-matrix (first two rows,last two columns):\n",arr_2d[:2,1:])

In [ ]:
print("\nelements greater than 5:",arr_2d[arr_2d > 5])

In [ ]:
print("elements at positions [0,2] and [2,0]:",arr_2d[[0,2],[2,0]])

In [ ]:
#BROAD CASTING

arr = np.array([1,2,3])
print("array + scalar:",arr + 5)

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [ ]:
b = np.array([10,20,30])
b

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
vector = np.array([10,20,30])
print("\nmatrix + vector:\n",matrix + vector)

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
vector = np.array([10,20,30,50])
print("\nmatrix + vector:\n",matrix + vector)

In [ ]:
try:
    matrix = np.array([[1,2,3],[4,5,6]])
    vectir = np.array([10,20])
    print(matrix + vector )
except ValueError as e:
    print("\nBroadcasting error :", e)

vector_reshaped = vector.reshape(2, 1)
print("\nMatrix + reshaped vector:\n", matrix + vector_reshaped)

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("from lists:\n",matrix)

In [ ]:
zero_matrix = np.zeros((3,3))
print("\nzeros matrix:\n",zero_matrix)

In [ ]:
ones_matrix = np.ones((2,4))
print("\nones matrix:\n",ones_matrix)

In [ ]:
identify_matrix = np.eye(3)
print("\nidentify matrix:\n",identify_matrix)


In [ ]:
diagonal_matrix = np.diag([1,2,3,4])
print("\nDiagonal matrix:\n",diagonal_matrix)

In [ ]:
random_matrix = np.random.random((3,3))
print("\nrandom matrix:\n",random_matrix)

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6,],[7,8]])
print(a)
print(b)
print("\nmatrix addition :\n",a + b)
print("\nmatrix multiplication:\n",np.matmul(a,b))
print("dot product (same as mutmul for 2D):\n",np.dot(a,b))
print("\nmatrix multiplication:\n", a @ b)
print("\nElement-wise multiplication:\n", a * b )
print("\nmatrix transpose:\n",a.T)

In [ ]:
np.random.seed(2)
np.random.random(3)

In [ ]:
print("random float [0,1):",np.random.random())
print("random integer [0,10);",np.random.randint(10))

In [ ]:
print("\n3 random floats:",np.random.random(3))
print("2x3 random floats:\n",np.random.random((2,3)))
print("5 random integers [1,100):",np.random.randint(1,100,5))

In [ ]:
#HOW TO GET UNIQUE ITEMS AND COUNTS

import numpy as np

arr = np.array([1,2,3,1,2,4,5,3,2,1])
print("original array:",arr)

unique_values = np.unique(arr)
print("unique values:",unique_values)

In [ ]:
unique_values,counts = np.unique(arr,return_counts = True)
print("\nvalue counts:")
for val, cnt  in  zip (unique_values,counts):
    print(f"{val}:{cnt}")

In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[1,2,3],[7,8,9]])
print("\n2D array:\n",arr_2d)
print("\nunique rows:\n",np.unique(arr_2d, axis = 0))

In [ ]:
#SWAPPING AXES OF A MATRIX

import numpy as np 

arr_3d = np.arange(24).reshape(2,3,4)
print("\n3D array (2,3,4):\n",arr_3d)
print("\nswap axes 0 and 1 (3,2,4):\n",np.swapaxes(arr_3d,0,1))


In [ ]:
#hOW TO REVERSE AN ARRAY 
arr = np.array([1,2,3,4,5])
print("original ae=rray:",arr)
print("reversed:",arr[::-1])

In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\noriginal 2D array:\n",arr_2d)
print("\nreversed rows:\n",arr_2d[::-1,:])
print("\nreversed columns:\n",arr_2d[:,::-1])
print("\nreversed rows and columns:\n",arr_2d[::-1,::-1])

In [44]:
#WORKING WITH MATHEMATICAL FORMULAS

def mse(y_true, y_pred):
    return np.mean((y_true - y_pred)**2)

y_true = np.array([1.0,2.0,3.0,4.0])
y_pred = np.array([0.9,2.1,2.9,4.2])

print("MSE:", mse(y_true,y_pred))

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.linspace(-5,5,10)
print("\nsigmoid values:",sigmoid(x))

def euclidean(a,b):
    return np.sqrt(np.sum((a - b) ** 2))

point1 = np.array([1,2,3])
point2 = np.array([4,5,6])
print("\neuclidean distance:",euclidean(point1,point2))

x = np.array([[1,1],[1,2],[1,3]])
y = np.array([[1],[2],[3]])
theta = np.linalg.inv(x.T @ x) @ x.T @ y
print("\nlinear regression coefficients:\n",theta)

MSE: 0.017500000000000022

sigmoid values: [0.00669285 0.02005754 0.0585369  0.1588691  0.36457644 0.63542356
 0.8411309  0.9414631  0.97994246 0.99330715]

euclidean distance: 5.196152422706632

linear regression coefficients:
 [[-1.77635684e-15]
 [ 1.00000000e+00]]


In [46]:
#HOW TO SAVE AND LOAD NUMPY OBJECTS

arr = np.array([1,2,3,4,5])

np.save('my_array.npy',arr)

loaded_arr = np.load('my_array.npy')
print("loaded array:",loaded_arr)



loaded array: [1 2 3 4 5]


In [48]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
np.savez('arrays.npz',arr1=arr1,arr2=arr2)

loaded = np.load('arrays.npz')
print("\nloaded arr1:",loaded['arr1'])
print("loaded arr2:",loaded['arr2'])


loaded arr1: [1 2 3]
loaded arr2: [4 5 6]


In [49]:
np.savetxt('array.txt',arr)
txt_arr = np.loadtxt('array.txt')
print("\nloaded from text file:",txt_arr)


loaded from text file: [1. 2. 3. 4. 5.]


In [51]:
np.savetxt('array.csv',arr.reshape(1,-1),delimiter = ',')
csv_arr = np.loadtxt('array.csv',delimiter=',')
print("\nloaded from csv:",csv_arr)


loaded from csv: [1. 2. 3. 4. 5.]
